[package]
name = "playing-around-with-opengl"
authors = ["Jane Lewis"]
version = "0.1.0"
edition = "2021"

[dependencies]
glutin = "0.28.0"
bytemuck = "1"
gl33 = { version = "0.2.1", features = ["println_debug"]}
